// Code generated by scripts/gen-api.mjs from /api/openapi.json (NetScope dev). DO NOT EDIT.
// Regenerate with `npm run gen:api` after backend API changes.

export interface ApiAckRequest {
	filter?: ApiEventFilter;
	ids?: number[];
	note?: string;
}

export interface ApiAckResponse {
	acknowledged: number;
}

export interface ApiActionRequest {
	params?: Record<string, unknown>;
}

export interface ApiAuditList {
	items: AuditEntry[];
	total: number;
}

export interface ApiBackupInfo {
	createdAt: string;
	name: string;
	size: number;
}

export interface ApiBulkRequest {
	action: string;
	group?: number;
	ids: number[];
	name?: string;
	params?: Record<string, unknown>;
	plugin?: string;
	tags?: string[];
	value?: string;
}

export interface ApiBulkResponse {
	affected: number;
	outcome?: PluginhostActionOutcome;
}

export interface ApiChallengeRequest {
	challenge: string;
}

export interface ApiCheckRunResult {
	check?: HealthcheckCheck;
	error?: string;
	latencyMs: number;
	ok: boolean;
}

export interface ApiClientInfo {
	host: string;
	ip: string;
	scheme: string;
}

export interface ApiCodeRequest {
	challenge: string;
	code: string;
}

export interface ApiCreateDeviceRequest {
	ip: string;
	mac: string;
	name: string;
}

export interface ApiCredentialUse {
	id: string;
	kind: string;
	name: string;
}

export interface ApiCredentialView {
	createdAt: string;
	description: string;
	id: number;
	lastUsedAt?: string;
	name: string;
	public: Record<string, string>;
	scope: PluginScope;
	secretsSet: string[];
	type: string;
	updatedAt: string;
	usedBy: ApiCredentialUse[];
}

export interface ApiCronResponse {
	error?: string;
	next: string[];
	text?: string;
	valid: boolean;
}

export interface ApiCveDetail {
	cve?: CveCVEInfo;
	devices: CveDeviceCVE[];
	disclaimer: string;
}

export interface ApiDashboard {
	activeRuns: PluginhostRunView[];
	availability24h?: number;
	certificates: InventoryCertView[];
	criticalEvents: EventsEvent[];
	cves: Record<string, number>;
	devices: ApiDeviceCounts;
	generatedAt: string;
	health: Record<string, number>;
	openEvents: Record<string, number>;
	plugins: ApiPluginStatus[];
	pluginsFailed: number;
	sites: FederationSite[];
	subnets: InventorySubnet[];
	topCves: ApiTopCVE[];
}

export interface ApiDeviceAction {
	confirm?: string;
	description?: string;
	label: string;
	name: string;
	params?: PluginField[];
	plugin: string;
	pluginName: string;
}

export interface ApiDeviceCVEList {
	disclaimer: string;
	items: CveDeviceCVE[];
}

export interface ApiDeviceCounts {
	ignored: number;
	new24h: number;
	offline: number;
	online: number;
	total: number;
	unknown: number;
}

export interface ApiDeviceCredential {
	id: number;
	name: string;
	rank: number;
	reason: string;
	type: string;
	usedBy: ApiCredentialUse[];
}

export interface ApiDeviceList {
	items: InventoryDeviceRow[];
	tookMs: number;
	total: number;
}

export interface ApiEventDetail {
	ackNote?: string;
	ackedAt?: string;
	ackedBy?: string;
	category: string;
	dedupKey?: string;
	deviceId?: number;
	deviceName?: string;
	id: number;
	label: string;
	message: string;
	notifications: RulesNotificationView[];
	payload: Record<string, unknown>;
	pluginId: string;
	prevRunId?: number;
	runId?: number;
	severity: string;
	site?: string;
	siteId?: number;
	title: string;
	ts: string;
	type: string;
}

export interface ApiEventFilter {
	categories?: string[];
	deviceId?: number;
	from?: string;
	minSeverity?: string;
	runId?: number;
	site?: string;
	text?: string;
	to?: string;
	types?: string[];
}

export interface ApiEventList {
	items: EventsEvent[];
	total: number;
}

export interface ApiFederationView {
	localName: string;
	protocol: number;
	settings: FederationSettingsView;
	site?: FederationSiteStatus;
	sites: ApiSiteRef[];
}

export interface ApiGraphEdgeRequest {
	childId: number;
	childPort: string;
	kind: string;
	label: string;
	parentId: number;
	parentPort: string;
}

export interface ApiGroupMembers {
	ids: number[];
}

export interface ApiHealthBoard {
	checks: HealthcheckCheck[];
	outages: HealthcheckOutage[];
	summary: Record<string, number>;
}

export interface ApiHealthResponse {
	database: string;
	status: string;
	uptimeSeconds: number;
	version: string;
}

export interface ApiIdResponse {
	id: number;
}

export interface ApiIgnoreRequest {
	cve: string;
	deviceId: number;
	ignored: boolean;
	note?: string;
}

export interface ApiIpRequest {
	ip: string;
}

export interface ApiLogLevelRequest {
	level: string;
}

export interface ApiLoginRequest {
	password: string;
	username: string;
}

export interface ApiLoginResponse {
	mfa?: ApiMfaChallenge;
	principal?: AuthPrincipal;
	user?: AuthUser;
}

export interface ApiMeResponse {
	principal?: AuthPrincipal;
	user?: AuthUser;
}

export interface ApiMergeRequest {
	sources: number[];
	target: number;
}

export interface ApiMetaResponse {
	credentialTypes: PluginCredentialType[];
	deviceActions: ApiDeviceAction[];
	deviceTypes: string[];
	eventTypes: PluginEventSpec[];
	priorities: string[];
	publicUrl: string;
	publishers: PluginhostPublisherInfo[];
	queryFields: InventoryQueryField[];
	scanners: ApiPluginShort[];
	severities: ApiSeverityInfo[];
	sortFields: string[];
	timeZone: string;
	version: string;
}

export interface ApiMfaChallenge {
	challenge: string;
	methods: string[];
}

export interface ApiMfaResponse {
	passkeys: AuthPasskey[];
	passkeysAvailable: boolean;
	recoveryCodes: number;
	required: boolean;
	rpId?: string;
	totp: boolean;
}

export interface ApiNotificationList {
	items: RulesNotificationView[];
	total: number;
}

export interface ApiOkResponse {
	ok: boolean;
}

export interface ApiPasskeyCreated {
	passkey?: AuthPasskey;
	recoveryCodes: string[];
}

export interface ApiPasskeyLoginRequest {
	challenge: string;
	credential: unknown;
}

export interface ApiPasskeyRequest {
	credential: unknown;
	name: string;
}

export interface ApiPasswordConfirm {
	password: string;
}

export interface ApiPasswordRequest {
	current: string;
	new: string;
}

export interface ApiPasswordResponse {
	password: string;
}

export interface ApiPluginShort {
	enabled: boolean;
	id: string;
	kind: string;
	name: string;
}

export interface ApiPluginStatus {
	enabled: boolean;
	id: string;
	kind: string;
	lastError?: string;
	lastRunAt?: string;
	lastStatus?: string;
	name: string;
	nextRun?: string;
	running: boolean;
}

export interface ApiRecoveryCodesResponse {
	recoveryCodes: string[];
}

export interface ApiRenameRequest {
	name: string;
}

export interface ApiRuleOrderRequest {
	ids: number[];
}

export interface ApiRuleTestRequest {
	event: RulesSimInput;
	rule?: RulesRule;
}

export interface ApiRunList {
	items: PluginhostRunView[];
	total: number;
}

export interface ApiRunRequest {
	scope?: PluginScope;
}

export interface ApiScanRequest {
	plugins: string[];
}

export interface ApiScanResponse {
	runs: Record<string, number>;
}

export interface ApiSendReportRequest {
	from?: string;
	publishers: string[];
	to?: string;
}

export interface ApiSeriesResponse {
	key: string;
	metric: string;
	points: TimeseriesPoint[];
	resolution: string;
	series: TimeseriesSeries[];
}

export interface ApiSeverityInfo {
	label: string;
	value: string;
}

export interface ApiSiteCreated {
	site?: FederationSite;
	token: string;
}

export interface ApiSiteRef {
	connected: boolean;
	contacted: boolean;
	id: number;
	linkUrl?: string;
	name: string;
	slug: string;
}

export interface ApiSiteToken {
	token: string;
}

export interface ApiSplitRequest {
	macs: string[];
}

export interface ApiSubnetView {
	access: string;
	cidr: string;
	createdAt: string;
	deviceCount: number;
	enabled: boolean;
	gateway: string;
	id: number;
	interface: string;
	name: string;
	notes: string;
	tunnel?: TunnelStatus;
	tunnelCredentialId?: number;
	updatedAt: string;
	vlan?: number;
}

export interface ApiSystemInfo {
	client: ApiClientInfo;
	configPath: string;
	dataDir: string;
	dbPath: string;
	dbSizeBytes: number;
	goVersion: string;
	goroutines: number;
	listen: string;
	logFormat: string;
	logLevel: string;
	memoryBytes: number;
	missingBinaries: Record<string, string[]>;
	plugins: number;
	schemaVersion: number;
	startedAt: string;
	timeZone: string;
	trustedProxies: string[];
	uptimeSeconds: number;
	vaultKeyId: string;
	vaultKeySource: string;
	version: string;
}

export interface ApiTokenCreated {
	info?: AuthToken;
	token: string;
}

export interface ApiTokenRequest {
	expiresAt?: string;
	name: string;
	scope: string;
}

export interface ApiTopCVE {
	cve: string;
	cvss: number;
	devices: number;
}

export interface ApiTotpConfirmRequest {
	code: string;
}

export interface ApiTotpSetupRequest {
	password?: string;
}

export interface ApiTunnelInput {
	config?: string;
	credentialId?: number;
	subnets?: string[];
}

export interface ApiTunnelOverview {
	available: boolean;
	reason?: string;
	tunnels: TunnelStatus[];
}

export interface ApiUploadResponse {
	name: string;
	path: string;
	size: number;
}

export interface ApiUserCreated {
	password?: string;
	user?: AuthUser;
}

export interface ApiVulnList {
	disclaimer: string;
	items: CveVulnRow[];
	total: number;
}

export interface ApiVulnStatus {
	cpeMatchCount: number;
	cveCount: number;
	disclaimer: string;
	empty: boolean;
	feeds: CveFeedStatus[];
	lastMatch?: CveMatchStatus;
	lastSync?: string;
	summary: Record<string, number>;
	syncError?: string;
	syncMode?: string;
	syncStatus?: string;
}

export interface AuditEntry {
	action: string;
	actor: string;
	actorType: string;
	after?: unknown;
	before?: unknown;
	entityId: string;
	entityType: string;
	id: number;
	ip: string;
	summary: string;
	ts: string;
}

export interface AuthPasskey {
	createdAt: string;
	id: number;
	lastUsedAt?: string;
	name: string;
	rpId: string;
}

export interface AuthPermission {
	critical?: boolean;
	group: string;
	hint: string;
	key: string;
	label: string;
}

export interface AuthPrincipal {
	admin: boolean;
	displayName?: string;
	kind: string;
	mfaSetup?: boolean;
	passwordChange?: boolean;
	permissions: string[];
	roleId: number;
	roleName: string;
	scope: string;
	tokenId?: number;
	tokenName?: string;
	userId: number;
	username: string;
}

export interface AuthRole {
	admin: boolean;
	createdAt: string;
	description: string;
	id: number;
	name: string;
	permissions: string[];
	require2fa: boolean;
	updatedAt: string;
	users: number;
}

export interface AuthRoleInput {
	description: string;
	name: string;
	permissions: string[];
	require2fa: boolean;
}

export interface AuthTOTPSetup {
	qr: string;
	secret: string;
	uri: string;
}

export interface AuthToken {
	createdAt: string;
	expiresAt?: string;
	id: number;
	lastUsedAt?: string;
	lastUsedIp?: string;
	name: string;
	owner: string;
	prefix: string;
	scope: string;
	userId: number;
}

export interface AuthUser {
	createdAt: string;
	disabled: boolean;
	displayName: string;
	email: string;
	id: number;
	lastLoginAt?: string;
	mfaRequired: boolean;
	mustChangePassword: boolean;
	passkeys: number;
	recoveryCodes: number;
	roleId: number;
	roleName: string;
	totp: boolean;
	updatedAt: string;
	username: string;
}

export interface AuthUserInput {
	disabled: boolean;
	displayName: string;
	email: string;
	password?: string;
	roleId: number;
	username: string;
}

export interface CveCPEMatch {
	criteria: string;
	part: string;
	product: string;
	update: string;
	vendor: string;
	version: string;
	versionEndExcluding?: string;
	versionEndIncluding?: string;
	versionStartExcluding?: string;
	versionStartIncluding?: string;
}

export interface CveCVEInfo {
	cpeMatches: CveCPEMatch[];
	cpeMatchesTotal: number;
	cvss?: number;
	cvssVersion: string;
	cwes: string[];
	description: string;
	id: string;
	inMirror: boolean;
	lastModified?: string;
	published?: string;
	refs: CveReference[];
	severity: string;
	status: string;
	url: string;
	vector: string;
}

export interface CveDeviceCVE {
	cpe: string;
	cve: string;
	cvss?: number;
	cvssVersion: string;
	cwes: string[];
	description: string;
	deviceId: number;
	deviceName: string;
	firstSeen: string;
	id: number;
	ignoreNote?: string;
	ignored: boolean;
	ignoredAt?: string;
	ignoredBy?: string;
	lastSeen: string;
	matchType: string;
	product: string;
	published?: string;
	refs: CveReference[];
	severity: string;
	source: string;
	vector: string;
	version: string;
}

export interface CveFeedStatus {
	cveCount: number;
	error?: string;
	lastModified: string;
	name: string;
	sha256: string;
	size: number;
	status: string;
	syncedAt?: string;
}

export interface CveMatchStatus {
	activeCves: number;
	at?: string;
	devices: number;
	error?: string;
	finished?: string;
	status: string;
}

export interface CveReference {
	tags?: string[];
	url: string;
}

export interface CveVulnRow {
	allIgnored: boolean;
	cve: string;
	cvss?: number;
	cvssVersion: string;
	description: string;
	devices: number;
	firstSeen: string;
	ignoredDevices: number;
	lastModified?: string;
	matchTypes: string[];
	products: string[];
	published?: string;
	severity: string;
	vector: string;
}

export interface EventsEvent {
	ackNote?: string;
	ackedAt?: string;
	ackedBy?: string;
	category: string;
	dedupKey?: string;
	deviceId?: number;
	deviceName?: string;
	id: number;
	label: string;
	message: string;
	payload: Record<string, unknown>;
	pluginId: string;
	runId?: number;
	severity: string;
	site?: string;
	siteId?: number;
	title: string;
	ts: string;
	type: string;
}

export interface FederationSettingsInput {
	centralUrl: string;
	fingerprint: string;
	localName: string;
	role: string;
	token?: string;
}

export interface FederationSettingsView {
	centralUrl: string;
	fingerprint: string;
	hasToken: boolean;
	localName: string;
	managed: boolean;
	role: string;
}

export interface FederationSite {
	connected: boolean;
	createdAt: string;
	devices: number;
	down: boolean;
	id: number;
	instance?: WireInstance;
	lastContact?: string;
	lastIp?: string;
	linkUrl: string;
	name: string;
	online: number;
	slug: string;
	status?: WireStatus;
	tokenPrefix: string;
	url: string;
}

export interface FederationSiteInput {
	name: string;
	url: string;
}

export interface FederationSiteStatus {
	active: boolean;
	buffered: number;
	connected: boolean;
	lastAttempt?: string;
	lastError?: string;
	lastSuccess?: string;
	nextAttempt?: string;
	oldestItem?: string;
	siteName?: string;
	syncing: boolean;
}

export interface FederationTestResult {
	durationMs: number;
	error?: string;
	ok: boolean;
	site?: string;
}

export interface HealthcheckCheck {
	availability?: Record<string, number>;
	config: HealthcheckCheckConfig;
	consecutiveFail: number;
	consecutiveOk: number;
	createdAt: string;
	deviceId?: number;
	deviceName?: string;
	enabled: boolean;
	failThreshold: number;
	id: number;
	intervalSeconds: number;
	lastCheckAt?: string;
	lastError?: string;
	lastLatencyMs?: number;
	lastOk?: boolean;
	latency24h?: TimeseriesPoint[];
	name: string;
	port: number;
	recoverThreshold: number;
	state: string;
	stateSince?: string;
	target: string;
	timeoutSeconds: number;
	type: string;
	updatedAt: string;
}

export interface HealthcheckCheckConfig {
	bodyMatch?: string;
	count?: number;
	degradedMs?: number;
	expectStatus?: string;
	followRedirects?: boolean;
	method?: string;
	minDays?: number;
	serverName?: string;
	url?: string;
	verifyTls?: boolean;
}

export interface HealthcheckOutage {
	checkId: number;
	checkName?: string;
	deviceId?: number;
	endedAt?: string;
	id: number;
	reason: string;
	seconds: number;
	startedAt: string;
	state: string;
}

export interface InventoryCertView {
	chainError?: string;
	chainValid: boolean;
	cipher?: string;
	daysLeft: number;
	deviceId: number;
	deviceName?: string;
	fingerprint: string;
	firstSeen: string;
	goneAt?: string;
	id: number;
	ip: string;
	issuer: string;
	issuerCn: string;
	keyBits: number;
	keyType: string;
	lastSeen: string;
	notAfter: string;
	notBefore: string;
	port: number;
	sans?: string[];
	selfSigned: boolean;
	serial: string;
	serverName?: string;
	signatureAlg: string;
	source: string;
	subjectCn: string;
	versions?: string[];
	weakCiphers?: string[];
	weakProtocols?: string[];
}

export interface InventoryContainerData {
	containers: InventoryContainerView[];
	images: InventoryImageView[];
}

export interface InventoryContainerView {
	composeProject?: string;
	composeService?: string;
	created: string;
	engine: string;
	firstSeen: string;
	goneAt?: string;
	id: string;
	image: string;
	imageId?: string;
	labels?: Record<string, string>;
	lastSeen: string;
	name: string;
	networks?: string[];
	ports?: PluginContainerPort[];
	rowId: number;
	source: string;
	state?: string;
	status?: string;
}

export interface InventoryCustomField {
	createdAt: string;
	description: string;
	id: number;
	key: string;
	label: string;
	sortOrder: number;
	type: string;
	updatedAt: string;
}

export interface InventoryDeviceDetail {
	certExpiry?: string;
	counts: Record<string, number>;
	createdSource: string;
	criticality: string;
	custom: Record<string, unknown>;
	cveCount: number;
	displayName: string;
	effectiveSources: Record<string, string>;
	facts: InventoryFactView[];
	firstSeen?: string;
	groups: InventoryGroupRef[];
	hasNotes: boolean;
	healthState?: string;
	hostname: string;
	hostnameSource: string;
	id: number;
	ip: string;
	ipHistory: InventoryIPView[];
	ips: string[];
	lastSeen?: string;
	location: string;
	mac: string;
	macList: InventoryMACView[];
	macs: string[];
	manual: Record<string, string>;
	maxCvss?: number;
	model: string;
	name: string;
	notes: string;
	online: boolean;
	onlineChangedAt?: string;
	os: string;
	osSource: string;
	owner: string;
	parentId?: number;
	parentName?: string;
	portCount: number;
	ports?: string[];
	presence: InventoryPresenceView[];
	refs: InventoryRefView[];
	site?: string;
	siteId?: number;
	siteRef?: InventorySiteRef;
	state: string;
	tags: string[];
	type: string;
	vendor: string;
}

export interface InventoryDeviceRow {
	certExpiry?: string;
	createdSource: string;
	criticality: string;
	custom: Record<string, unknown>;
	cveCount: number;
	displayName: string;
	firstSeen?: string;
	groups: InventoryGroupRef[];
	hasNotes: boolean;
	healthState?: string;
	hostname: string;
	hostnameSource: string;
	id: number;
	ip: string;
	ips: string[];
	lastSeen?: string;
	location: string;
	mac: string;
	macs: string[];
	maxCvss?: number;
	model: string;
	name: string;
	online: boolean;
	onlineChangedAt?: string;
	os: string;
	osSource: string;
	owner: string;
	parentId?: number;
	parentName?: string;
	portCount: number;
	ports?: string[];
	site?: string;
	siteId?: number;
	state: string;
	tags: string[];
	type: string;
	vendor: string;
}

export interface InventoryDeviceUpdate {
	criticality?: string;
	custom?: Record<string, unknown>;
	displayName?: string;
	hostname?: string;
	location?: string;
	model?: string;
	notes?: string;
	os?: string;
	owner?: string;
	state?: string;
	tags?: string[];
	type?: string;
	vendor?: string;
}

export interface InventoryDiffItem {
	change: string;
	deviceId: number;
	deviceName: string;
	key: string;
	kind: string;
	new?: string;
	old?: string;
}

export interface InventoryDiffResult {
	a: InventoryDiffSide;
	b: InventoryDiffSide;
	items: InventoryDiffItem[];
	summary: Record<string, number>;
}

export interface InventoryDiffSide {
	finished?: string;
	kind: string;
	partial?: boolean;
	pluginId?: string;
	pluginName?: string;
	runId?: number;
	time: string;
}

export interface InventoryFactView {
	extra?: unknown;
	firstSeen: string;
	kind: string;
	lastSeen: string;
	source: string;
	value: string;
}

export interface InventoryGraph {
	edges: InventoryGraphEdge[];
	nodes: InventoryGraphNode[];
	tookMs: number;
}

export interface InventoryGraphEdge {
	childPort?: string;
	id: string;
	kind: string;
	label?: string;
	origin: string;
	parentPort?: string;
	protected: boolean;
	relationId?: number;
	source: string;
	target: string;
}

export interface InventoryGraphNode {
	deviceId?: number;
	id: string;
	image?: string;
	ip?: string;
	kind: string;
	label: string;
	online: boolean;
	state?: string;
	subnet?: string;
	tags?: string[];
	type?: string;
	vendor?: string;
}

export interface InventoryGroup {
	color: string;
	createdAt: string;
	description: string;
	id: number;
	kind: string;
	memberCount: number;
	name: string;
	query: string;
	updatedAt: string;
}

export interface InventoryGroupRef {
	color?: string;
	id: number;
	name: string;
}

export interface InventoryHTTPView {
	apps?: PluginDetectedApp[];
	contentType?: string;
	faviconHash?: number;
	faviconMd5?: string;
	finalUrl?: string;
	firstSeen: string;
	headers?: Record<string, string>;
	id: number;
	ip: string;
	lastSeen: string;
	port: number;
	redirects?: string[];
	scheme: string;
	server?: string;
	source: string;
	statusCode: number;
	title?: string;
	url: string;
}

export interface InventoryIPView {
	firstSeen: string;
	goneAt?: string;
	ip: string;
	lastSeen: string;
	mac: string;
	source: string;
	subnetId?: number;
}

export interface InventoryImageView {
	created: string;
	engine: string;
	firstSeen: string;
	id: string;
	inUse: number;
	size: number;
	tags?: string[];
}

export interface InventoryMACView {
	firstSeen: string;
	lastSeen: string;
	mac: string;
	randomized: boolean;
	source: string;
	vendor: string;
}

export interface InventoryObservationView {
	data: unknown;
	id: number;
	pluginId: string;
	raw?: string;
	runId?: number;
	target: string;
	ts: string;
}

export interface InventoryPackageList {
	items: InventoryPackageView[];
	total: number;
}

export interface InventoryPackageView {
	arch: string;
	firstSeen: string;
	lastSeen: string;
	manager: string;
	name: string;
	version: string;
}

export interface InventoryPortView {
	cpes: string[];
	extraInfo: string;
	firstSeen: string;
	goneAt?: string;
	id: number;
	ip: string;
	lastSeen: string;
	port: number;
	product: string;
	proto: string;
	service: string;
	source: string;
	state: string;
	tunnel: string;
	version: string;
}

export interface InventoryPresenceView {
	lastSeen: string;
	missed: number;
	plugin: string;
}

export interface InventoryQueryField {
	description: string;
	example: string;
	field: string;
	ops: string;
}

export interface InventoryRefView {
	data?: unknown;
	lastSeen: string;
	ref: string;
	source: string;
}

export interface InventoryRelation {
	childId: number;
	childName: string;
	childPort: string;
	firstSeen: string;
	id: number;
	kind: string;
	label: string;
	lastSeen: string;
	parentId: number;
	parentName: string;
	parentPort: string;
	protected: boolean;
	source: string;
}

export interface InventorySavedView {
	columns: string[];
	createdAt: string;
	id: number;
	name: string;
	query: string;
	sort: string;
	updatedAt: string;
}

export interface InventorySiteRef {
	id: number;
	name: string;
	remoteId?: number;
	slug: string;
	url?: string;
}

export interface InventorySubnet {
	access: string;
	cidr: string;
	createdAt: string;
	deviceCount: number;
	enabled: boolean;
	gateway: string;
	id: number;
	interface: string;
	name: string;
	notes: string;
	tunnelCredentialId?: number;
	updatedAt: string;
	vlan?: number;
}

export interface InventoryTagCount {
	count: number;
	tag: string;
}

export interface InventoryTimelineEntry {
	change: string;
	eventId?: number;
	kind: string;
	runId?: number;
	severity?: string;
	text: string;
	ts: string;
}

export interface LoggingEntry {
	attrs?: Record<string, unknown>;
	level: string;
	msg: string;
	plugin?: string;
	seq: number;
	time: string;
}

export interface PluginAction {
	confirm?: string;
	description?: string;
	label: string;
	name: string;
	params?: PluginField[];
	scope: string;
}

export interface PluginActionResult {
	data?: unknown;
	message: string;
}

export interface PluginCondition {
	equals: unknown[];
	field: string;
}

export interface PluginContainerPort {
	ip?: string;
	privatePort: number;
	publicPort?: number;
	type: string;
}

export interface PluginCredentialType {
	description: string;
	label: string;
	schema: PluginSchema;
	type: string;
}

export interface PluginDetectedApp {
	confidence: string;
	cpe?: string;
	evidence?: string;
	name: string;
	version?: string;
}

export interface PluginEventSpec {
	category: string;
	defaultSeverity: string;
	description: string;
	label: string;
	payload: PluginPayloadField[];
	source: string;
	type: string;
}

export interface PluginEventView {
	acknowledged?: boolean;
	at: string;
	category: string;
	deviceId?: number;
	deviceIp?: string;
	deviceLink?: string;
	deviceMac?: string;
	deviceName?: string;
	escalated?: boolean;
	id: number;
	label: string;
	link?: string;
	message?: string;
	payload?: Record<string, unknown>;
	severity: string;
	site?: string;
	title: string;
	type: string;
}

export interface PluginField {
	advanced?: boolean;
	credentialTypes?: string[];
	default?: unknown;
	description?: string;
	group?: string;
	key: string;
	label: string;
	multi?: boolean;
	multiline?: boolean;
	options?: PluginOption[];
	placeholder?: string;
	required?: boolean;
	secret?: boolean;
	type: string;
	validation?: PluginValidation;
	visibleIf?: PluginCondition;
	widget?: string;
}

export interface PluginInfo {
	binaries?: string[];
	defaultConcurrency: number;
	defaultEnabled: boolean;
	defaultRetries: number;
	defaultSchedule: string;
	/** Nanosekunden */
	defaultTimeoutNs: number;
	description: string;
	id: string;
	kind: string;
	name: string;
	presence: boolean;
	targets: string;
	version: string;
}

export interface PluginNotification {
	body?: string;
	createdAt: string;
	events?: PluginEventView[];
	id: number;
	kind: string;
	link?: string;
	priority: string;
	ruleId?: number;
	ruleName?: string;
	title: string;
}

export interface PluginOption {
	label: string;
	value: string;
}

export interface PluginPayloadField {
	description: string;
	key: string;
	type: string;
}

export interface PluginSchema {
	fields: PluginField[];
}

export interface PluginScope {
	allSubnets: boolean;
	devices?: number[];
	groups?: number[];
	query?: string;
	subnets?: string[];
	tags?: string[];
}

export interface PluginValidation {
	format?: string;
	max?: number;
	min?: number;
	pattern?: string;
}

export interface PluginhostActionOutcome {
	error?: string;
	finished: boolean;
	result?: PluginActionResult;
	runId: number;
	status: string;
}

export interface PluginhostConfigInput {
	concurrency?: number;
	enabled?: boolean;
	retries?: number;
	retryBackoffSeconds?: number;
	schedule?: string;
	scope?: PluginScope;
	settings?: Record<string, unknown>;
	timeoutSeconds?: number;
}

export interface PluginhostConfigView {
	concurrency: number;
	enabled: boolean;
	retries: number;
	retryBackoffSeconds: number;
	schedule: string;
	scheduleText: string;
	scope: PluginScope;
	settings: Record<string, unknown>;
	timeoutSeconds: number;
	updatedAt: string;
}

export interface PluginhostPluginView {
	actions: PluginAction[];
	backlog: number;
	capabilities: string[];
	config?: PluginhostConfigView;
	info: PluginInfo;
	lastRun?: PluginhostRunView;
	missingBinaries?: string[];
	nextRun?: string;
	running?: PluginhostRunView;
	schema: PluginSchema;
}

export interface PluginhostProgress {
	done: number;
	total: number;
}

export interface PluginhostPublisherInfo {
	enabled: boolean;
	id: string;
	name: string;
}

export interface PluginhostRunLog {
	attrs?: Record<string, unknown>;
	id: number;
	level: string;
	msg: string;
	ts: string;
}

export interface PluginhostRunView {
	attempt: number;
	createdAt: string;
	durationMs: number;
	error?: string;
	finishedAt?: string;
	id: number;
	kind: string;
	notBefore?: string;
	params: Record<string, unknown>;
	parentRunId?: number;
	pluginId: string;
	pluginName: string;
	progress?: PluginhostProgress;
	requestedBy: string;
	scope: PluginScope;
	startedAt?: string;
	stats: Record<string, unknown>;
	status: string;
	trigger: string;
}

export interface ReportsCVELine {
	cve: string;
	cvss: number;
	detail: string;
	device: string;
}

export interface ReportsCertLine {
	daysLeft: number;
	device: string;
	endpoint: string;
	notAfter: string;
	subject: string;
}

export interface ReportsChangeReport {
	cveBySeverity: Record<string, number>;
	devices: Record<string, number>;
	eventCounts: Record<string, number>;
	expiringCerts: ReportsCertLine[];
	failedRuns: Record<string, number>;
	from: string;
	generatedAt: string;
	important: ReportsEventLine[];
	newCves: ReportsCVELine[];
	newDevices: ReportsDeviceLine[];
	openCritical: number;
	openHigh: number;
	outages: ReportsOutageLine[];
	to: string;
}

export interface ReportsDeviceLine {
	at?: string;
	id: number;
	ip: string;
	name: string;
	vendor?: string;
}

export interface ReportsEventLine {
	acked: boolean;
	device?: string;
	id: number;
	severity: string;
	title: string;
	ts: string;
	type: string;
}

export interface ReportsOutageLine {
	check: string;
	duration: string;
	ongoing: boolean;
	seconds: number;
	started: string;
	state: string;
}

export interface RulesAction {
	batchMinutes?: number;
	escalateAfterMinutes?: number;
	escalatePriority?: string;
	escalatePublisher?: string;
	mode: string;
	priority: string;
	publisher: string;
	quietHours?: RulesQuietHours;
	throttle?: string;
}

export interface RulesActionPlan {
	deliverAt: string;
	escalateAt?: string;
	mode: string;
	priority: string;
	publisher: string;
	publisherEnabled: boolean;
	publisherName: string;
	quiet?: string;
	skipped?: string;
	throttled: boolean;
}

export interface RulesCondResult {
	condition: string;
	detail: string;
	ok: boolean;
}

export interface RulesConditions {
	deviceQuery?: string;
	deviceStates?: string[];
	eventTypes: string[];
	groups?: number[];
	minSeverity?: string;
	onlyUnknown?: boolean;
	payload?: RulesPayloadCond[];
	sites?: number[];
	subnets?: string[];
	tags?: string[];
	timeWindow?: RulesTimeWindow;
}

export interface RulesNotificationView {
	attempts: number;
	createdAt: string;
	deliverAfter: string;
	error?: string;
	eventIds: number[];
	id: number;
	kind: string;
	priority: string;
	publisher: string;
	ruleId?: number;
	ruleName?: string;
	sentAt?: string;
	status: string;
	title?: string;
}

export interface RulesPayloadCond {
	field: string;
	op: string;
	value: string;
}

export interface RulesQuietHours {
	allowUrgent: boolean;
	behavior: string;
	from: string;
	to: string;
}

export interface RulesRule {
	actions: RulesAction[];
	builtin?: string;
	conditions: RulesConditions;
	createdAt: string;
	description: string;
	enabled: boolean;
	id: number;
	name: string;
	sortOrder: number;
	stop: boolean;
	updatedAt: string;
}

export interface RulesSimInput {
	deliver?: boolean;
	deviceId?: number;
	message?: string;
	payload?: Record<string, unknown>;
	severity?: string;
	siteId?: number;
	title?: string;
	type: string;
}

export interface RulesSimResult {
	actions: RulesActionPlan[];
	conditions: RulesCondResult[];
	delivery?: Record<string, string>;
	matched: boolean;
	note?: string;
	preview?: PluginNotification;
	previewText: string;
}

export interface RulesTimeWindow {
	days?: number[];
	from: string;
	to: string;
}

export interface SettingsSystem {
	deviceTypes: string[];
	hostnamePriority: string[];
	maxParallelRuns: number;
	metricsPublic: boolean;
	observationRawMaxKb: number;
	offlineAfterMissed: number;
	publicUrl: string;
}

export interface TimeseriesPoint {
	avg: number;
	count: number;
	max: number;
	min: number;
	t: string;
}

export interface TimeseriesSeries {
	deviceId?: number;
	id: number;
	key?: string;
	metric: string;
	unit?: string;
}

export interface TunnelStatus {
	addresses: string[];
	credentialId: number;
	endpoint: string;
	error?: string;
	interface: string;
	lastHandshake?: string;
	name: string;
	publicKey: string;
	rxBytes: number;
	since: string;
	state: string;
	subnets: string[];
	txBytes: number;
	warnings: string[];
}

export interface TunnelTestResult {
	latencyMs?: number;
	message: string;
	ok: boolean;
}

export interface VaultCredentialInput {
	description: string;
	name: string;
	scope?: PluginScope;
	type: string;
	values: Record<string, unknown>;
}

export interface WgconfSummary {
	addresses: string[];
	allowedIps: string[];
	endpoint: string;
	keepalive: number;
	mtu?: number;
	peerPublicKey: string;
	presharedKey: boolean;
	publicKey: string;
	warnings: string[];
}

export interface WireBatch {
	epoch: string;
	instance: WireInstance;
	items: WireItem[];
	protocol: number;
	status?: WireStatus;
}

export interface WireInstance {
	hostname?: string;
	startedAt: string;
	url?: string;
	version: string;
}

export interface WireItem {
	at: string;
	data: unknown;
	kind: string;
	seq: number;
}

export interface WirePluginStatus {
	error?: string;
	id: string;
	lastRun?: string;
	name: string;
	scheduled: boolean;
	status?: string;
}

export interface WireResponse {
	acked: number;
	protocol: number;
	resync?: boolean;
	site: string;
}

export interface WireStatus {
	buffered: number;
	devices: number;
	oldestItem?: string;
	online: number;
	plugins: WirePluginStatus[];
	subnets: WireSubnet[];
	syncing?: boolean;
}

export interface WireSubnet {
	access?: string;
	cidr: string;
	devices: number;
	enabled: boolean;
	gateway?: string;
	name?: string;
}

/** All documented endpoints: ApiPaths[path][method] = { query, body, response }. */

export interface ApiPaths {
	'/api/v1/audit': {
		/** Audit-Log */
		get: {
			query: {
				entity?: string | null;
				id?: string | null;
				action?: string | null;
				q?: string | null;
				limit?: number | null;
				offset?: number | null;
			};
			body: never;
			response: ApiAuditList;
		};
	};
	'/api/v1/auth/2fa': {
		/** Eigene Zwei-Faktor-Anmeldung: TOTP, Passkeys, Wiederherstellungscodes */
		get: { query: never; body: never; response: ApiMfaResponse };
	};
	'/api/v1/auth/2fa/recovery': {
		/** Neue Wiederherstellungscodes erzeugen (alte werden ungültig) */
		post: { query: never; body: ApiPasswordConfirm; response: ApiRecoveryCodesResponse };
	};
	'/api/v1/auth/2fa/totp': {
		/** TOTP einrichten (Geheimnis und QR-Code; aktiv erst nach Bestätigung) */
		post: { query: never; body: ApiTotpSetupRequest; response: AuthTOTPSetup };
	};
	'/api/v1/auth/2fa/totp/confirm': {
		/** TOTP mit dem ersten Code aktivieren */
		post: { query: never; body: ApiTotpConfirmRequest; response: ApiRecoveryCodesResponse };
	};
	'/api/v1/auth/2fa/totp/disable': {
		/** TOTP abschalten (Passwort erforderlich) */
		post: { query: never; body: ApiPasswordConfirm; response: ApiOkResponse };
	};
	'/api/v1/auth/login': {
		/** Anmelden (setzt Session-Cookie oder verlangt den zweiten Faktor) */
		post: { query: never; body: ApiLoginRequest; response: ApiLoginResponse };
	};
	'/api/v1/auth/login/passkey': {
		/** Anmeldung mit Passkey abschließen */
		post: { query: never; body: ApiPasskeyLoginRequest; response: ApiLoginResponse };
	};
	'/api/v1/auth/login/passkey/options': {
		/** Passkey-Anmeldung beginnen (Optionen für navigator.credentials.get) */
		post: { query: never; body: ApiChallengeRequest; response: Record<string, unknown> };
	};
	'/api/v1/auth/login/recovery': {
		/** Anmeldung mit Wiederherstellungscode abschließen */
		post: { query: never; body: ApiCodeRequest; response: ApiLoginResponse };
	};
	'/api/v1/auth/login/totp': {
		/** Anmeldung mit TOTP-Code abschließen */
		post: { query: never; body: ApiCodeRequest; response: ApiLoginResponse };
	};
	'/api/v1/auth/logout': {
		/** Abmelden */
		post: { query: never; body: never; response: ApiOkResponse };
	};
	'/api/v1/auth/me': {
		/** Aktueller Benutzer mit Rolle und Berechtigungen */
		get: { query: never; body: never; response: ApiMeResponse };
	};
	'/api/v1/auth/passkeys': {
		/** Passkey registrieren */
		post: { query: never; body: ApiPasskeyRequest; response: ApiPasskeyCreated };
	};
	'/api/v1/auth/passkeys/options': {
		/** Passkey-Registrierung beginnen (Optionen für navigator.credentials.create) */
		post: { query: never; body: never; response: Record<string, unknown> };
	};
	'/api/v1/auth/passkeys/{id}': {
		/** Passkey umbenennen */
		patch: { query: never; body: ApiRenameRequest; response: ApiOkResponse };
		/** Passkey entfernen */
		delete: { query: never; body: never; response: ApiOkResponse };
	};
	'/api/v1/auth/password': {
		/** Eigenes Passwort ändern (beendet andere Sessions) */
		put: { query: never; body: ApiPasswordRequest; response: ApiOkResponse };
	};
	'/api/v1/certificates': {
		/** Alle aktiven Zertifikate nach Ablaufdatum */
		get: { query: { days?: number | null }; body: never; response: InventoryCertView[] };
	};
	'/api/v1/credentials': {
		/** Vault-Einträge (ohne Secrets) */
		get: { query: never; body: never; response: ApiCredentialView[] };
		/** Credential anlegen (verschlüsselt gespeichert) */
		post: { query: never; body: VaultCredentialInput; response: ApiCredentialView };
	};
	'/api/v1/credentials/types': {
		/** Credential-Typen mit Formular-Schema */
		get: { query: never; body: never; response: PluginCredentialType[] };
	};
	'/api/v1/credentials/{id}': {
		/** Ein Credential (ohne Secrets) */
		get: { query: never; body: never; response: ApiCredentialView };
		/** Credential ändern (Secret-Felder mit ******** bleiben unverändert) */
		put: { query: never; body: VaultCredentialInput; response: ApiCredentialView };
		/** Credential löschen (nur wenn unbenutzt) */
		delete: { query: never; body: never; response: ApiOkResponse };
	};
	'/api/v1/cron/describe': {
		/** Cron-Ausdruck prüfen und in Klartext beschreiben */
		get: { query: { expr: string }; body: never; response: ApiCronResponse };
	};
	'/api/v1/custom-fields': {
		/** Custom-Field-Definitionen */
		get: { query: never; body: never; response: InventoryCustomField[] };
		/** Custom Field anlegen */
		post: { query: never; body: InventoryCustomField; response: InventoryCustomField };
	};
	'/api/v1/custom-fields/{id}': {
		/** Custom Field ändern */
		put: { query: never; body: InventoryCustomField; response: InventoryCustomField };
		/** Custom Field löschen (inkl. Werte) */
		delete: { query: never; body: never; response: ApiOkResponse };
	};
	'/api/v1/dashboard': {
		/** Kennzahlen für das Dashboard */
		get: { query: { site?: string | null }; body: never; response: ApiDashboard };
	};
	'/api/v1/devices': {
		/** Geräteliste mit Filter-Query-Sprache */
		get: {
			query: {
				q?: string | null;
				sort?: string | null;
				site?: string | null;
				limit?: number | null;
				offset?: number | null;
				ports?: boolean | null;
			};
			body: never;
			response: ApiDeviceList;
		};
		/** Gerät manuell anlegen */
		post: { query: never; body: ApiCreateDeviceRequest; response: ApiIdResponse };
	};
	'/api/v1/devices/bulk': {
		/** Massenaktion (Tags, Gruppe, Zustand, Kritikalität, Löschen, Plugin-Aktion wie WOL) */
		post: { query: never; body: ApiBulkRequest; response: ApiBulkResponse };
	};
	'/api/v1/devices/merge': {
		/** Geräte zusammenführen */
		post: { query: never; body: ApiMergeRequest; response: ApiOkResponse };
	};
	'/api/v1/devices/{id}': {
		/** Gerätedetail */
		get: { query: never; body: never; response: InventoryDeviceDetail };
		/** Manuelle Daten ändern */
		patch: { query: never; body: InventoryDeviceUpdate; response: InventoryDeviceDetail };
		/** Gerät löschen (Events bleiben) */
		delete: { query: never; body: never; response: ApiOkResponse };
	};
	'/api/v1/devices/{id}/actions/{plugin}/{action}': {
		/** Geräteaktion eines Plugins (z. B. WOL) */
		post: { query: never; body: ApiActionRequest; response: PluginhostActionOutcome };
	};
	'/api/v1/devices/{id}/certificates': {
		/** Zertifikate */
		get: { query: { history?: boolean | null }; body: never; response: InventoryCertView[] };
	};
	'/api/v1/devices/{id}/containers': {
		/** Container und Images */
		get: { query: { history?: boolean | null }; body: never; response: InventoryContainerData };
	};
	'/api/v1/devices/{id}/credentials': {
		/** Passende Zugangsdaten (nach Geltungsbereich, spezifischste zuerst) */
		get: { query: never; body: never; response: ApiDeviceCredential[] };
	};
	'/api/v1/devices/{id}/cves': {
		/** CVEs eines Geräts */
		get: { query: { ignored?: boolean | null }; body: never; response: ApiDeviceCVEList };
	};
	'/api/v1/devices/{id}/events': {
		/** Events des Geräts */
		get: { query: { limit?: number | null; offset?: number | null }; body: never; response: ApiEventList };
	};
	'/api/v1/devices/{id}/health': {
		/** Health-Checks des Geräts */
		get: { query: never; body: never; response: HealthcheckCheck[] };
	};
	'/api/v1/devices/{id}/http': {
		/** HTTP-Endpunkte und erkannte Web-Apps */
		get: { query: never; body: never; response: InventoryHTTPView[] };
	};
	'/api/v1/devices/{id}/inventory': {
		/** Strukturiertes Inventar je Quelle (SSH, SNMP, UPnP …) */
		get: { query: never; body: never; response: Record<string, unknown> };
	};
	'/api/v1/devices/{id}/ips': {
		/** IP-Adresse von Hand vergeben (z. B. für VMs, deren Hypervisor keine Adressen meldet) */
		post: { query: never; body: ApiIpRequest; response: InventoryDeviceDetail };
	};
	'/api/v1/devices/{id}/ips/{ip}': {
		/** Von Hand vergebene IP-Adresse entfernen */
		delete: { query: never; body: never; response: InventoryDeviceDetail };
	};
	'/api/v1/devices/{id}/observations': {
		/** Rohdaten pro Plugin */
		get: {
			query: { plugin?: string | null; limit?: number | null };
			body: never;
			response: InventoryObservationView[];
		};
	};
	'/api/v1/devices/{id}/packages': {
		/** Installierte Pakete */
		get: {
			query: { q?: string | null; limit?: number | null; offset?: number | null };
			body: never;
			response: InventoryPackageList;
		};
	};
	'/api/v1/devices/{id}/ports': {
		/** Ports & Dienste */
		get: { query: { history?: boolean | null }; body: never; response: InventoryPortView[] };
	};
	'/api/v1/devices/{id}/relations': {
		/** Beziehungen (Eltern/Kinder, Topologie) */
		get: { query: never; body: never; response: InventoryRelation[] };
	};
	'/api/v1/devices/{id}/scan': {
		/** Scanner jetzt für dieses Gerät ausführen */
		post: { query: never; body: ApiScanRequest; response: ApiScanResponse };
	};
	'/api/v1/devices/{id}/split': {
		/** MAC-Adressen in ein neues Gerät abspalten */
		post: { query: never; body: ApiSplitRequest; response: ApiIdResponse };
	};
	'/api/v1/devices/{id}/timeline': {
		/** Historie (Events und Zustandsänderungen) */
		get: { query: { limit?: number | null }; body: never; response: InventoryTimelineEntry[] };
	};
	'/api/v1/devices/{id}/timeseries': {
		/** Zeitreihen (z. B. icmp.rtt_ms, icmp.loss_pct) */
		get: {
			query: {
				metric?: string | null;
				key?: string | null;
				from?: string | null;
				to?: string | null;
				points?: number | null;
			};
			body: never;
			response: ApiSeriesResponse;
		};
	};
	'/api/v1/diff': {
		/** Zwei Läufe (runA/runB) oder zwei Zeitpunkte (from/to) vergleichen */
		get: {
			query: {
				runA?: number | null;
				runB?: number | null;
				from?: string | null;
				to?: string | null;
				device?: number | null;
			};
			body: never;
			response: InventoryDiffResult;
		};
	};
	'/api/v1/events': {
		/** Events mit Filter */
		get: {
			query: {
				type?: string | null;
				category?: string | null;
				severity?: string | null;
				device?: number | null;
				run?: number | null;
				acked?: boolean | null;
				from?: string | null;
				to?: string | null;
				q?: string | null;
				site?: string | null;
				limit?: number | null;
				offset?: number | null;
			};
			body: never;
			response: ApiEventList;
		};
	};
	'/api/v1/events/ack': {
		/** Events quittieren (IDs oder Filter) */
		post: { query: never; body: ApiAckRequest; response: ApiAckResponse };
	};
	'/api/v1/events/counts': {
		/** Offene Events je Schweregrad */
		get: { query: never; body: never; response: Record<string, number> };
	};
	'/api/v1/events/types': {
		/** Katalog der Event-Typen */
		get: { query: never; body: never; response: PluginEventSpec[] };
	};
	'/api/v1/events/{id}': {
		/** Ein Event inkl. Benachrichtigungen */
		get: { query: never; body: never; response: ApiEventDetail };
	};
	'/api/v1/federation': {
		/** Rolle der Instanz, Zustand der Anbindung und Standorte */
		get: { query: never; body: never; response: ApiFederationView };
		/** Rolle festlegen (eigenständig, Standort, Zentrale) und die Zentrale eines Standorts eintragen */
		put: { query: never; body: FederationSettingsInput; response: ApiFederationView };
	};
	'/api/v1/federation/ingest': {
		/** Zentrale: Lieferung eines Standorts annehmen (nur mit Standort-Token nss_…; gzip erlaubt) */
		post: { query: never; body: WireBatch; response: WireResponse };
	};
	'/api/v1/federation/resync': {
		/** Standort: vollständigen Abgleich mit der Zentrale anstoßen */
		post: { query: never; body: never; response: unknown };
	};
	'/api/v1/federation/test': {
		/** Standort: Verbindung zur Zentrale prüfen */
		post: { query: never; body: never; response: FederationTestResult };
	};
	'/api/v1/groups': {
		/** Gerätegruppen */
		get: { query: never; body: never; response: InventoryGroup[] };
		/** Gruppe anlegen (manuell oder regelbasiert per Filter) */
		post: { query: never; body: InventoryGroup; response: InventoryGroup };
	};
	'/api/v1/groups/{id}': {
		/** Gruppe ändern */
		put: { query: never; body: InventoryGroup; response: InventoryGroup };
		/** Gruppe löschen */
		delete: { query: never; body: never; response: ApiOkResponse };
	};
	'/api/v1/groups/{id}/members': {
		/** Mitglieder einer Gruppe */
		get: { query: never; body: never; response: ApiGroupMembers };
	};
	'/api/v1/health': {
		/** Health-Endpoint (ohne Anmeldung) */
		get: { query: never; body: never; response: ApiHealthResponse };
	};
	'/api/v1/health-checks': {
		/** Health-Checks */
		get: { query: { device?: number | null }; body: never; response: HealthcheckCheck[] };
		/** Health-Check anlegen */
		post: { query: never; body: HealthcheckCheck; response: HealthcheckCheck };
	};
	'/api/v1/health-checks/{id}': {
		/** Ein Health-Check */
		get: { query: never; body: never; response: HealthcheckCheck };
		/** Health-Check ändern */
		put: { query: never; body: HealthcheckCheck; response: HealthcheckCheck };
		/** Health-Check löschen */
		delete: { query: never; body: never; response: ApiOkResponse };
	};
	'/api/v1/health-checks/{id}/latency': {
		/** Latenz-Zeitreihe eines Checks */
		get: {
			query: { from?: string | null; to?: string | null; points?: number | null };
			body: never;
			response: ApiSeriesResponse;
		};
	};
	'/api/v1/health-checks/{id}/outages': {
		/** Ausfallhistorie eines Checks */
		get: { query: { limit?: number | null }; body: never; response: HealthcheckOutage[] };
	};
	'/api/v1/health-checks/{id}/run': {
		/** Check sofort ausführen */
		post: { query: never; body: never; response: ApiCheckRunResult };
	};
	'/api/v1/health/board': {
		/** Statusboard aller Checks mit Verfügbarkeit und Ausfällen */
		get: { query: never; body: never; response: ApiHealthBoard };
	};
	'/api/v1/meta': {
		/** Kataloge und Metadaten für die Oberfläche */
		get: { query: never; body: never; response: ApiMetaResponse };
	};
	'/api/v1/notifications': {
		/** Benachrichtigungsverlauf */
		get: {
			query: {
				status?: string | null;
				publisher?: string | null;
				event?: number | null;
				rule?: number | null;
				limit?: number | null;
				offset?: number | null;
			};
			body: never;
			response: ApiNotificationList;
		};
	};
	'/api/v1/permissions': {
		/** Katalog der Berechtigungen für Rollen */
		get: { query: never; body: never; response: AuthPermission[] };
	};
	'/api/v1/plugins': {
		/** Alle Plugins mit Schema, Konfiguration und Status */
		get: { query: never; body: never; response: PluginhostPluginView[] };
	};
	'/api/v1/plugins/{id}': {
		/** Ein Plugin */
		get: { query: never; body: never; response: PluginhostPluginView };
	};
	'/api/v1/plugins/{id}/actions/{action}': {
		/** Plugin-Aktion ausführen */
		post: { query: { wait?: number | null }; body: ApiActionRequest; response: PluginhostActionOutcome };
	};
	'/api/v1/plugins/{id}/config': {
		/** Konfiguration ändern (aktiv, Zeitplan, Timeout, Retries, Parallelität, Scope, Einstellungen) – wirkt sofort */
		put: { query: never; body: PluginhostConfigInput; response: PluginhostPluginView };
	};
	'/api/v1/plugins/{id}/run': {
		/** Jetzt ausführen */
		post: { query: never; body: ApiRunRequest; response: ApiIdResponse };
	};
	'/api/v1/plugins/{id}/test': {
		/** Testnachricht über einen Publisher senden */
		post: { query: never; body: never; response: ApiOkResponse };
	};
	'/api/v1/publishers': {
		/** Verfügbare Publisher */
		get: { query: never; body: never; response: PluginhostPublisherInfo[] };
	};
	'/api/v1/reports/changes': {
		/** Änderungsbericht für einen Zeitraum (json, md, pdf) */
		get: {
			query: { from?: string | null; to?: string | null; format?: string | null };
			body: never;
			response: ReportsChangeReport;
		};
	};
	'/api/v1/reports/inventory': {
		/** Inventar-Export (csv, json, pdf) */
		get: {
			query: { format?: string | null; q?: string | null; site?: string | null };
			body: never;
			response: Blob;
			binary: true;
		};
	};
	'/api/v1/reports/send': {
		/** Änderungsbericht jetzt über Publisher versenden */
		post: { query: never; body: ApiSendReportRequest; response: ApiOkResponse };
	};
	'/api/v1/roles': {
		/** Rollen auflisten */
		get: { query: never; body: never; response: AuthRole[] };
		/** Rolle anlegen */
		post: { query: never; body: AuthRoleInput; response: AuthRole };
	};
	'/api/v1/roles/{id}': {
		/** Rolle ändern (Administrator: nur Beschreibung und 2FA-Pflicht) */
		put: { query: never; body: AuthRoleInput; response: AuthRole };
		/** Rolle löschen (nur ohne Benutzer) */
		delete: { query: never; body: never; response: ApiOkResponse };
	};
	'/api/v1/rules': {
		/** Benachrichtigungsregeln */
		get: { query: never; body: never; response: RulesRule[] };
		/** Regel anlegen */
		post: { query: never; body: RulesRule; response: RulesRule };
	};
	'/api/v1/rules/order': {
		/** Auswertungsreihenfolge der Regeln setzen (atomar) */
		put: { query: never; body: ApiRuleOrderRequest; response: RulesRule[] };
	};
	'/api/v1/rules/test': {
		/** Regel mit simuliertem Event testen (gespeicherte Regel per ID-Route oder ungespeicherte im Body) */
		post: { query: never; body: ApiRuleTestRequest; response: RulesSimResult };
	};
	'/api/v1/rules/{id}': {
		/** Eine Regel */
		get: { query: never; body: never; response: RulesRule };
		/** Regel ändern */
		put: { query: never; body: RulesRule; response: RulesRule };
		/** Regel löschen */
		delete: { query: never; body: never; response: ApiOkResponse };
	};
	'/api/v1/rules/{id}/test': {
		/** Gespeicherte Regel mit simuliertem Event testen */
		post: { query: never; body: RulesSimInput; response: RulesSimResult };
	};
	'/api/v1/runs': {
		/** Laufhistorie */
		get: {
			query: {
				plugin?: string | null;
				status?: string | null;
				kind?: string | null;
				scope?: string | null;
				before?: number | null;
				limit?: number | null;
				offset?: number | null;
			};
			body: never;
			response: ApiRunList;
		};
	};
	'/api/v1/runs/active': {
		/** Laufende Läufe */
		get: { query: never; body: never; response: PluginhostRunView[] };
	};
	'/api/v1/runs/{id}': {
		/** Ein Lauf */
		get: { query: never; body: never; response: PluginhostRunView };
	};
	'/api/v1/runs/{id}/cancel': {
		/** Lauf abbrechen */
		post: { query: never; body: never; response: ApiOkResponse };
	};
	'/api/v1/runs/{id}/logs': {
		/** Protokoll eines Laufs */
		get: {
			query: { after?: number | null; limit?: number | null };
			body: never;
			response: PluginhostRunLog[];
		};
	};
	'/api/v1/sites': {
		/** Zentrale: Standorte mit Verbindungszustand und letzter Meldung */
		get: { query: never; body: never; response: FederationSite[] };
		/** Zentrale: Standort anlegen (liefert das Token einmalig) */
		post: { query: never; body: FederationSiteInput; response: ApiSiteCreated };
	};
	'/api/v1/sites/{id}': {
		/** Zentrale: ein Standort */
		get: { query: never; body: never; response: FederationSite };
		/** Zentrale: Standort umbenennen oder Adresse ändern */
		patch: { query: never; body: FederationSiteInput; response: FederationSite };
		/** Zentrale: Standort mit allen gelieferten Geräten und Events entfernen */
		delete: { query: never; body: never; response: unknown };
	};
	'/api/v1/sites/{id}/token': {
		/** Zentrale: neues Token für einen Standort (das alte gilt sofort nicht mehr) */
		post: { query: never; body: never; response: ApiSiteToken };
	};
	'/api/v1/stream': {
		/** Live-Updates (Server-Sent Events) */
		get: { query: { topics?: string | null }; body: never; response: unknown };
	};
	'/api/v1/subnets': {
		/** Subnetze (mit Tunnel-Zustand) */
		get: { query: never; body: never; response: ApiSubnetView[] };
		/** Subnetz anlegen */
		post: { query: never; body: InventorySubnet; response: ApiSubnetView };
	};
	'/api/v1/subnets/{id}': {
		/** Subnetz ändern */
		put: { query: never; body: InventorySubnet; response: ApiSubnetView };
		/** Subnetz löschen */
		delete: { query: never; body: never; response: ApiOkResponse };
	};
	'/api/v1/system/backups': {
		/** Backups auflisten */
		get: { query: never; body: never; response: ApiBackupInfo[] };
		/** Backup der Datenbank erstellen */
		post: { query: never; body: never; response: ApiBackupInfo };
	};
	'/api/v1/system/backups/{name}': {
		/** Backup herunterladen */
		get: { query: never; body: never; response: Blob; binary: true };
		/** Backup löschen */
		delete: { query: never; body: never; response: ApiOkResponse };
	};
	'/api/v1/system/info': {
		/** Systeminformationen */
		get: { query: never; body: never; response: ApiSystemInfo };
	};
	'/api/v1/system/loglevel': {
		/** Log-Level zur Laufzeit ändern */
		put: { query: never; body: ApiLogLevelRequest; response: ApiLogLevelRequest };
	};
	'/api/v1/system/logs': {
		/** Anwendungsprotokoll (Ringpuffer) */
		get: {
			query: { level?: string | null; plugin?: string | null; q?: string | null; limit?: number | null };
			body: never;
			response: LoggingEntry[];
		};
	};
	'/api/v1/system/restore': {
		/** Datenbank wiederherstellen (multipart „file“ oder JSON {name}); startet die Dienste neu */
		post: { query: never; body: never; response: ApiOkResponse };
	};
	'/api/v1/system/settings': {
		/** Systemeinstellungen */
		get: { query: never; body: never; response: SettingsSystem };
		/** Systemeinstellungen speichern */
		put: { query: never; body: SettingsSystem; response: SettingsSystem };
	};
	'/api/v1/system/vault/rotate': {
		/** Master-Key des Vaults rotieren */
		post: { query: never; body: never; response: Record<string, string> };
	};
	'/api/v1/tags': {
		/** Alle Tags mit Anzahl */
		get: { query: never; body: never; response: InventoryTagCount[] };
	};
	'/api/v1/tokens': {
		/** API-Tokens auflisten (eigene; mit Benutzerverwaltung alle) */
		get: { query: never; body: never; response: AuthToken[] };
		/** API-Token erstellen (Klartext nur in dieser Antwort) */
		post: { query: never; body: ApiTokenRequest; response: ApiTokenCreated };
	};
	'/api/v1/tokens/{id}': {
		/** API-Token widerrufen (eigene; mit Benutzerverwaltung alle) */
		delete: { query: never; body: never; response: ApiOkResponse };
	};
	'/api/v1/topology': {
		/** Topologie-Graph (Knoten und Kanten) */
		get: {
			query: {
				subnet?: string | null;
				tag?: string | null;
				q?: string | null;
				site?: string | null;
				containers?: boolean | null;
				ignored?: boolean | null;
			};
			body: never;
			response: InventoryGraph;
		};
	};
	'/api/v1/topology/edges': {
		/** Manuelle Kanten */
		get: { query: never; body: never; response: InventoryRelation[] };
		/** Manuelle (geschützte) Kante anlegen */
		post: { query: never; body: ApiGraphEdgeRequest; response: ApiIdResponse };
	};
	'/api/v1/topology/edges/{id}': {
		/** Kante löschen */
		delete: { query: never; body: never; response: ApiOkResponse };
	};
	'/api/v1/tunnels': {
		/** WireGuard-Tunnel und ihr Zustand */
		get: { query: never; body: never; response: ApiTunnelOverview };
	};
	'/api/v1/tunnels/inspect': {
		/** WireGuard-Konfiguration prüfen (liefert nur öffentliche Angaben und Hinweise) */
		post: { query: never; body: ApiTunnelInput; response: WgconfSummary };
	};
	'/api/v1/tunnels/test': {
		/** Verbindungstest: Handshake mit dem WireGuard-Server (bis 10 s) */
		post: { query: never; body: ApiTunnelInput; response: TunnelTestResult };
	};
	'/api/v1/uploads': {
		/** Datei hochladen (multipart „file“, z. B. für Importer) */
		post: { query: never; body: never; response: ApiUploadResponse };
	};
	'/api/v1/users': {
		/** Benutzer auflisten */
		get: { query: never; body: never; response: AuthUser[] };
		/** Benutzer anlegen (ohne Passwort wird eins erzeugt; Änderung beim ersten Login) */
		post: { query: never; body: AuthUserInput; response: ApiUserCreated };
	};
	'/api/v1/users/{id}': {
		/** Benutzer */
		get: { query: never; body: never; response: AuthUser };
		/** Benutzer ändern (Name, Rolle, deaktiviert) */
		put: { query: never; body: AuthUserInput; response: AuthUser };
		/** Benutzer löschen (mit Tokens und Sessions) */
		delete: { query: never; body: never; response: ApiOkResponse };
	};
	'/api/v1/users/{id}/2fa/reset': {
		/** Zweiten Faktor zurücksetzen (TOTP, Passkeys, Codes) */
		post: { query: never; body: never; response: ApiOkResponse };
	};
	'/api/v1/users/{id}/password': {
		/** Neues Start-Passwort erzeugen (Änderung beim nächsten Login) */
		post: { query: never; body: never; response: ApiPasswordResponse };
	};
	'/api/v1/views': {
		/** Gespeicherte Geräteansichten */
		get: { query: never; body: never; response: InventorySavedView[] };
		/** Ansicht speichern */
		post: { query: never; body: InventorySavedView; response: InventorySavedView };
	};
	'/api/v1/views/{id}': {
		/** Ansicht ändern */
		put: { query: never; body: InventorySavedView; response: InventorySavedView };
		/** Ansicht löschen */
		delete: { query: never; body: never; response: ApiOkResponse };
	};
	'/api/v1/vulnerabilities': {
		/** CVE-Liste über alle Geräte (heuristischer Abgleich) */
		get: {
			query: {
				min?: number | null;
				q?: string | null;
				product?: string | null;
				device?: number | null;
				ignored?: boolean | null;
				sort?: string | null;
				limit?: number | null;
				offset?: number | null;
				site?: string | null;
			};
			body: never;
			response: ApiVulnList;
		};
	};
	'/api/v1/vulnerabilities/ignore': {
		/** CVE für ein Gerät als irrelevant markieren (oder zurücknehmen) */
		post: { query: never; body: ApiIgnoreRequest; response: ApiOkResponse };
	};
	'/api/v1/vulnerabilities/status': {
		/** NVD-Sync-Status und Übersicht */
		get: { query: never; body: never; response: ApiVulnStatus };
	};
	'/api/v1/vulnerabilities/{cve}': {
		/** Details einer CVE mit betroffenen Geräten */
		get: { query: never; body: never; response: ApiCveDetail };
	};
	'/metrics': {
		/** Prometheus-Metriken */
		get: { query: never; body: never; response: unknown };
	};
}
