#!/usr/bin/env node
// Generates src/lib/api/generated.ts from the backend's OpenAPI document.
//
//   npm run gen:api                         # $NETSCOPE_API/api/openapi.json (default http://127.0.0.1:18080)
//   npm run gen:api -- path/to/openapi.json # from a file
//   npm run gen:api -- http://host:8080     # from another instance
//
// The spec is produced by internal/api/openapi.go via reflection over the Go types, so the
// generated interfaces mirror the JSON tags exactly: fields without `omitempty` (and not
// pointers) are required, everything else is optional. Note that Go encodes nil slices and
// maps as `null` – treat list responses defensively (`?? []`).
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as prettier from 'prettier';

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, '../src/lib/api/generated.ts');

async function load(src) {
	if (/^https?:\/\//.test(src)) {
		const url = src.endsWith('.json') ? src : src.replace(/\/$/, '') + '/api/openapi.json';
		const res = await fetch(url);
		if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
		return res.json();
	}
	return JSON.parse(await readFile(src, 'utf8'));
}

const src = process.argv[2] ?? process.env.NETSCOPE_API ?? 'http://127.0.0.1:18080';
const spec = await load(src);

const ident = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const key = (k) => (ident.test(k) ? k : JSON.stringify(k));

/** @returns {string} TypeScript type for a JSON schema */
function tsType(s, indent = '') {
	if (!s || Object.keys(s).length === 0) return 'unknown';
	if (s.$ref) return s.$ref.split('/').pop();
	switch (s.type) {
		case 'string':
			return 'string';
		case 'integer':
		case 'number':
			return 'number';
		case 'boolean':
			return 'boolean';
		case 'array': {
			const t = tsType(s.items, indent);
			return /^[A-Za-z0-9_]+$/.test(t) ? `${t}[]` : `Array<${t}>`;
		}
		case 'object':
			if (s.properties) return objectType(s, indent);
			if (s.additionalProperties !== undefined)
				return `Record<string, ${tsType(s.additionalProperties, indent)}>`;
			return 'Record<string, unknown>';
	}
	return 'unknown';
}

function objectType(s, indent = '') {
	const req = new Set(s.required ?? []);
	const inner = indent + '\t';
	const lines = Object.keys(s.properties)
		.sort()
		.map((p) => {
			const prop = s.properties[p];
			const doc = prop.description ? `${inner}/** ${prop.description} */\n` : '';
			return `${doc}${inner}${key(p)}${req.has(p) ? '' : '?'}: ${tsType(prop, inner)};`;
		});
	return `{\n${lines.join('\n')}\n${indent}}`;
}

const parts = [];
parts.push(
	`// Code generated by scripts/gen-api.mjs from /api/openapi.json (NetScope ${spec.info?.version ?? '?'}). DO NOT EDIT.\n` +
		`// Regenerate with \`npm run gen:api\` after backend API changes.\n`
);

const schemas = spec.components?.schemas ?? {};
for (const name of Object.keys(schemas).sort()) {
	const s = schemas[name];
	if (s.type === 'object' && s.properties) parts.push(`export interface ${name} ${objectType(s)}\n`);
	else parts.push(`export type ${name} = ${tsType(s)};\n`);
}

// Operations: ApiPaths[path][method] = { query; body; response }
const methods = ['get', 'post', 'put', 'patch', 'delete'];
const pathLines = [];
for (const p of Object.keys(spec.paths).sort()) {
	const ops = spec.paths[p];
	const opLines = [];
	for (const m of methods) {
		const op = ops[m];
		if (!op) continue;
		const qp = (op.parameters ?? []).filter((x) => x.in === 'query');
		const query = qp.length
			? `{ ${qp.map((x) => `${key(x.name)}${x.required ? '' : '?'}: ${x.schema?.type === 'integer' || x.schema?.type === 'number' ? 'number' : x.schema?.type === 'boolean' ? 'boolean' : 'string'}${x.required ? '' : ' | null'}`).join('; ')} }`
			: 'never';
		const body = op.requestBody
			? tsType(op.requestBody.content['application/json'].schema, '\t\t\t')
			: 'never';
		const okCode = Object.keys(op.responses ?? {}).find((c) => c !== 'default');
		const content = okCode ? op.responses[okCode].content : undefined;
		let response = 'unknown';
		let binary = false;
		if (content?.['application/json']) response = tsType(content['application/json'].schema, '\t\t\t');
		else if (content) {
			response = 'Blob';
			binary = true;
		}
		const doc = op.summary ? `\t\t/** ${op.summary} */\n` : '';
		opLines.push(
			`${doc}\t\t${m}: { query: ${query}; body: ${body}; response: ${response};${binary ? ' binary: true;' : ''} };`
		);
	}
	pathLines.push(`\t${JSON.stringify(p)}: {\n${opLines.join('\n')}\n\t};`);
}
parts.push(`/** All documented endpoints: ApiPaths[path][method] = { query, body, response }. */\n`);
parts.push(`export interface ApiPaths {\n${pathLines.join('\n')}\n}\n`);

const config = (await prettier.resolveConfig(out)) ?? {};
const formatted = await prettier.format(parts.join('\n'), { ...config, filepath: out });
await writeFile(out, formatted);
console.log(`wrote ${out} (${Object.keys(schemas).length} schemas, ${Object.keys(spec.paths).length} paths)`);
