// Package all imports every bundled plugin so that it registers itself.
package all

import (
	_ "netscope/internal/plugins/arpscan"
	_ "netscope/internal/plugins/cleanup"
	_ "netscope/internal/plugins/csv"
	_ "netscope/internal/plugins/cve"
	_ "netscope/internal/plugins/diff"
	_ "netscope/internal/plugins/dns"
	_ "netscope/internal/plugins/docker"
	_ "netscope/internal/plugins/email"
	_ "netscope/internal/plugins/healthcheck"
	_ "netscope/internal/plugins/http"
	_ "netscope/internal/plugins/icmp"
	_ "netscope/internal/plugins/mdns"
	_ "netscope/internal/plugins/n8n"
	_ "netscope/internal/plugins/netalertx"
	_ "netscope/internal/plugins/netbios"
	_ "netscope/internal/plugins/nmap"
	_ "netscope/internal/plugins/nmap_udp"
	_ "netscope/internal/plugins/ntfy"
	_ "netscope/internal/plugins/openwrt"
	_ "netscope/internal/plugins/oui"
	_ "netscope/internal/plugins/proxmox"
	_ "netscope/internal/plugins/report"
	_ "netscope/internal/plugins/snmp"
	_ "netscope/internal/plugins/ssh"
	_ "netscope/internal/plugins/telegram"
	_ "netscope/internal/plugins/tls"
	_ "netscope/internal/plugins/topology"
	_ "netscope/internal/plugins/upnp"
	_ "netscope/internal/plugins/webhook"
	_ "netscope/internal/plugins/wol"
)
